Algoritmo "atividade_2"

Var
   numero_1, numero_2, resultado : caracter
   operacao: caracter

Inicio
   Escreva ("Digite o primeiro número: ")
   Leia (numero_1)
   Escreva ("Digite o segundo número: ")
   Leia (numero_2)
   
   se (numero_1 > numero_2) então
    escreva ("numero_1 maior")
   fimse
    
   se (numero_2 > numero_1) então
    escreva ("numero_2 maior")
   fimse
   
   se (numero_1 = numero_2) então
    escreva ("numeros iguais")
   fimse

Fimalgoritmo